name: Plugins Build

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build_package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: "windows-latest"
            mono: ""
            csound-bin: "csound-windows_x86_64-6.16.2.exe"

          - os: "ubuntu-latest"
            mono: "mono"
            csound-bin: ""

          - os: "macos-latest"
            mono: "mono"
            csound-bin: "csound-MacOS_x86_64-6.16.2.dmg"

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Bootstrap VCPKG (windows)
        if: startsWith(matrix.os, 'windows')
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Bootstrap VCPKG (unix)
        if: "!startsWith(matrix.os, 'windows')"
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Setup VCPKG cache
        shell: bash
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/csound/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "csound"
          -password "${{ secrets.GITHUB_TOKEN }}"

      # TODO import Csound build
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "csound/csound"
          tag: "6.16.2"
          fileName: ${{ matrix.csound-bin }}

      - name: Generate CMake Build
        run: cmake -B build -S . -DUSE_VCPKG=1

      - name: Build Plugins
        run: cmake --build build --config Release
