name: Plugins Build

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build_package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        version: ["6.17.0"]
        include:
          - os: "windows-latest"
            mono: ""
            csound-bin: "csound-6.17.0-windows-x64-installer.zip"
            packages: cuda

          # - os: "ubuntu-latest"
          #   mono: "mono"
          #   csound-bin: ""
          #   packages: cuda

          - os: "macos-latest"
            mono: "mono"
            csound-bin: "csound-MacOS_x86_64-6.17.0.dmg"
            packages: cuda

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Install system packages (windows)
        if: startsWith(matrix.os, 'windows')
        run: chocolatey install ${{ matrix.packages }}

      - name: Install system packages (linux)
        if: "startsWith(matrix.os, 'ubuntu')"
        run: sudo apt-get install ${{ matrix.packages }}

      - name: Install system packages (mac)
        if: "startsWith(matrix.os, 'macos')"
        run: homebrew install ${{ matrix.packages }}

      - name: Bootstrap VCPKG (windows)
        if: startsWith(matrix.os, 'windows')
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Bootstrap VCPKG (linux/mac)
        if: "!startsWith(matrix.os, 'windows')"
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Setup VCPKG cache
        shell: bash
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/csound/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "csound"
          -password "${{ secrets.GITHUB_TOKEN }}"

      - uses: robinraju/release-downloader@v1.5
        with:
          repository: "csound/csound"
          tag: ${{ matrix.version }}
          fileName: ${{ matrix.csound-bin }}
          out-file-path: "downloads"

      - name: Install Csound (windows)
        if: startsWith(matrix.os, 'windows')
        working-directory: .\downloads
        run: |
          7z x ${{ matrix.csound-bin }}
          Start-Process (Get-ChildItem -Filter *.exe .) -ArgumentList "/SP /SILENT /SUPPRESSMSGBOXES"
          ls "C:\Program Files\Csound6_x64"

      - name: Install Csound (unix)
        if: "!startsWith(matrix.os, 'windows')"
        run: |
          7z x ${{ matrix.csound-bin }}
          ./downloads/

      - name: Generate CMake build
        run: cmake -S . -B build -DUSE_VCPKG=1

      - name: Build plugins
        run: cmake --build build --config Release
